In [1]:
# Numerical arrays.
import numpy as np

# Permutations and combinations.
import itertools as it

In [3]:
# The number of nodes in one of our graphs.
n = 3

In [6]:
# The permutations of n things.
list(it.permutations(range(n)))

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

In [7]:
# The number of permutations is n!
len(list(it.permutations(range(n))))

6

In [8]:
# The identity matrix with n rows and n columns.
I = np.eye(n, dtype=int)

I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
# Print all permutation matrices of size n.
for p in it.permutations(range(n)):
    print(I[list(p)])

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]
[[0 1 0]
 [0 0 1]
 [1 0 0]]
[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]]


In [14]:
# The 3x3 identity matrix.
I3 = np.eye(3, dtype=int)

In [22]:
# Pick one of the permutation matrices as an example.
M1 = I3[[0,2,1]]

M1

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [23]:
# Transpose of M1 - swap rows and columns.
M1.T

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [24]:
# M1 is symmetric.
M1 == M1.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
# M1 is symmetric.
(M1 == M1.T).all()

True

In [26]:
# M1 is symmetric.
np.all(M1 == M1.T)

True

In [27]:
# A different example.
M2 = I3[[2,0,1]]

M2

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [28]:
# Transpose of M2 - swap rows and columns.
M2.T

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [29]:
# M2 is not symmetric.
M2 == M2.T

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
# M2 is not symmetric.
np.all(M2 == M2.T)

False

In [32]:
# Multiply M1 by itself.
M1 @ M1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
# Multiply M2 by itself.
M2 @ M2

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [34]:
# Multiply M2 by its transpose.
M2.T @ M2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
# Multiply M2 by its transpose.
M2 @ M2.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
# An adjacency matrix.
A1 = np.array([[0,1,1],[1,0,0],[1,0,0]])

A1

array([[0, 1, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [39]:
# Another adjacency matrtix.
A2 = np.array([[0,1,0], [1,0,1], [0,1,0]])

A2

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [48]:
# Look for permutation matrices that transform A1 into A2.
Pmats = []
for p in it.permutations(range(N)):
    P = I[list(p)]
    if np.all(P.T @ A1 @ P == A2):
        Pmats.append(I[list(p)])
        print(p)
        print(I[list(p)])
        print()

(1, 0, 2)
[[0 1 0]
 [1 0 0]
 [0 0 1]]

(1, 2, 0)
[[0 1 0]
 [0 0 1]
 [1 0 0]]



In [49]:
# The permutations moving A1 to A2.
Pmats

[array([[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]]),
 array([[0, 1, 0],
        [0, 0, 1],
        [1, 0, 0]])]

In [50]:
A2

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [51]:
Pmats[0].T @ A1 @ Pmats[0]

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [52]:
Pmats[1].T @ A1 @ Pmats[1]

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [53]:
# Symmetries of A1.
Pmats = []
for p in it.permutations(range(N)):
    P = I[list(p)]
    if np.all(P.T @ A1 @ P == A1):
        Pmats.append(I[list(p)])
        print(p)
        print(I[list(p)])
        print()

(0, 1, 2)
[[1 0 0]
 [0 1 0]
 [0 0 1]]

(0, 2, 1)
[[1 0 0]
 [0 0 1]
 [0 1 0]]

