In [17]:
import numpy as np

import itertools as it

In [18]:
N = 3

In [19]:
list(it.permutations(range(N)))

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

In [20]:
len(list(it.permutations(range(N))))

6

In [21]:
I = np.eye(N, dtype=int)

I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
for p in it.permutations(range(N)):
    print(I[list(p)])

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]
[[0 1 0]
 [0 0 1]
 [1 0 0]]
[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]]


In [23]:
A1 = np.array([[0,1,1],[1,0,0],[1,0,0]])

A1

array([[0, 1, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [24]:
A2 = np.array([[0,1,0], [1,0,1], [0,1,0]])

A2

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [26]:
for p in it.permutations(range(N)):
    P = I[list(p)]
    if np.all(P.T @ A1 @ P == A2):
        print(p)

(1, 0, 2)
(1, 2, 0)
