In [1]:
# Numerical arrays.
import numpy as np

# Permutations.
import itertools as it

## range()

***

In [2]:
?range

Init signature: range(self, /, *args, **kwargs)
Docstring:     
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).
Type:           type
Subclasses:     

In [3]:
range(10)

range(0, 10)

In [4]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
L = ['a', 'b', 'c', 'd']

list(range(len(L)))

[0, 1, 2, 3]

In [7]:
list(range(2, 10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
# Java: for (i = 2; i < 10; i += 3)
list(range(2, 10, 3))

[2, 5, 8]

## Slicing

***


In [13]:
s = "Hello, world!"

s[7]

'w'

In [15]:
for i in range(3, 7):
    print(s[i])

l
o
,
 


In [14]:
s[3:7]

'lo, '

In [16]:
s[1:9:2]

'el,w'

In [17]:
# 0 is the default in front of first colon.
s[:9]

'Hello, wo'

In [19]:
# len(s) is the default value after first colon.
s[9:]

'rld!'

In [21]:
# Default step is 1.
s[2:6:]

'llo,'

## Permutations

***

In [25]:
# N
N = 3

# A list of integers up to N.
L = list(range(N))

# Show.
L

[0, 1, 2]

https://docs.python.org/3/library/itertools.html#itertools.permutations


In [26]:
# Generate all permutations of L.
for p in it.permutations(L):
  print(p)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


## Matrices

***

In [28]:
# N
N = 3

# Entries are [0, 1, 2, ..., N-1] in order.
M = np.arange(N**2)

# Show.
M

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
type(M)

numpy.ndarray

In [31]:
# N
N = 3

# Square matrix with N rows, N columns.
# Entries are [0, 1, 2, ..., N-1] in order.
M = np.arange(N**2).reshape((N,N))

# Show.
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
# First row.
M[0]

array([0, 1, 2])

In [33]:
# Second row, third column.
M[1, 2]

5

In [34]:
# Second row, third column.
M[(1, 2)]

5

In [40]:
# First column.
M[:, 0]

array([0, 3, 6])

In [42]:
# Bottom right four entries.
M[1:, 1:]

array([[4, 5],
       [7, 8]])

In [43]:
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
# Permute the rows.
M[[1,2,0]]

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [46]:
# Permute the columns.
M[:, [1,2,0]]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])